/*
 * nama : apriani magfira
 * stambuk : 13020180058
 * tanggal/waktu : 10 mei 2020 : 21.30 
 */
package view;

import controller.Service;
import controller.ServiceJdbc;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import model.Employee;


public class EmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form EmplyeeForm
     */
    //private Service service;
    private ServiceJdbc service;
    public EmployeeForm() {
        initComponents();
        //service = new Service();
        service = new ServiceJdbc();
        runTime();
    }
    private void runTime(){
        Timer t = new Timer();
        t.schedule(new TimerTask() {
            @Override
            public void run() {
                showData();
            }
        }, 0, 3000);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfNation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        bSave = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(634, 310));
        setPreferredSize(new java.awt.Dimension(634, 310));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jPanel1.add(tfId);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 70, 230, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("EMPLOYEE DATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 4, 260, 40);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Name");
        jPanel2.add(jLabel3);
        jPanel2.add(tfName);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 120, 230, 30);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText("Nation");
        jPanel3.add(jLabel4);
        jPanel3.add(tfNation);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 170, 230, 30);

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 30, 310, 240);

        bSave.setText("SAVE");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave);
        bSave.setBounds(20, 220, 80, 23);

        bUpdate.setText("UPDATE");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(bUpdate);
        bUpdate.setBounds(110, 220, 80, 23);

        bDelete.setText("DELETE");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete);
        bDelete.setBounds(210, 220, 80, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // now save to temporary database
        service.save(getData());
        
        clear();
        // now we need  show data to table
        showData();
    }//GEN-LAST:event_bSaveActionPerformed
    private Employee getData(){
        String id = tfId.getText();
        String name = tfName.getText();
        String nation = tfNation.getText();
        
        // create Employee class
        Employee e = new Employee();
        e.setId(id);
        e.setName(name);
        e.setNation(nation);
        return e;
    }
    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        service.update(getData());
        
        clear();
        showData();
    }//GEN-LAST:event_bUpdateActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int iData = tableData.getSelectedRow();
        
        tfId.setText(tableData.getValueAt(iData, 0).toString());
        tfName.setText(tableData.getValueAt(iData, 1).toString());
        tfNation.setText(tableData.getValueAt(iData, 2).toString());
        // get Valueat is getting data value on iData as row and next value is column
    }//GEN-LAST:event_tableDataMouseClicked

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        service.delete(getData());
        
        clear();
        showData();
    }//GEN-LAST:event_bDeleteActionPerformed
    private void clear(){
        tfId.setText("");
        tfName.setText("");
        tfNation.setText("");
    }
    private DefaultTableModel model;
    private void showData(){
        Object[] column = {"ID", "NAME", "NATION"};
        Object[][] data = new Object[service.getEmployees().size()][3];
        // value 3 means much column on table
        for (int i = 0; i < service.getEmployees().size(); i++) {
            Employee e = service.getEmployees().get(i);
            Object[] arr_data = {e.getId(), e.getName(), e.getNation()};
            data[i] = arr_data;
        }
        model = new DefaultTableModel(data, column);
        tableData.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNation;
    // End of variables declaration//GEN-END:variables
}
